# Generated by Django 3.1.7 on 2021-08-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=14)),
                ('price', models.CharField(max_length=14)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
